name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  python-test:
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.0
      - name: Build dsmlpstoragecontrollerclient Python package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
          echo "DIST_WHEEL=dist/$(ls dist | grep '.whl')" >> $GITHUB_ENV
          echo "DIST_SDIST=dist/$(ls dist | grep '.tar.gz')" >> $GITHUB_ENV
        env:
          DSMLP_STORAGE_CONTROLLER_CA: ${{ secrets.DSMLP_STORAGE_CONTROLLER_CA }}
          DSMLP_STORAGE_CONTROLLER_CERT: ${{ secrets.DSMLP_STORAGE_CONTROLLER_CERT }}
          DSMLP_STORAGE_CONTROLLER_KEY: ${{ secrets.DSMLP_STORAGE_CONTROLLER_KEY }}
          DSMLP_STORAGE_CONTROLLER_PORT: ${{ secrets.DSMLP_STORAGE_CONTROLLER_PORT }}
          DSMLP_STORAGE_CONTROLLER_DNS: ${{ secrets.DSMLP_STORAGE_CONTROLLER_DNS }}
          DSMLP_STORAGE_CONTROLLER_CLIENT_CERT: ${{ secrets.DSMLP_STORAGE_CONTROLLER_CLIENT_CERT }}
          DSMLP_STORAGE_CONTROLLER_CLIENT_KEY: ${{ secrets.DSMLP_STORAGE_CONTROLLER_CLIENT_KEY }}
      - name: Run action for creating release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.DIST_WHEEL }}
            ${{ env.DIST_SDIST }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
