name: tag-version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.NHP002_PERSONAL_ACCESS_TOKEN }}

jobs:
  check-next-tag-version:
    name: Check next tag version
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.dry-run-version-bump.outputs.new_tag }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - name: Perform dry run of github-tag-action
        id: dry-run-version-bump
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: patch
  update-init-version:
    name: Update __init__ version
    runs-on: ubuntu-latest
    needs: check-next-tag-version
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - name: Write version to __init__
        run: |
          git config --global user.email "nhp002@ucsd.edu"
          git config --global user.name "Naval Patel"
          PACKAGE_TAG=${{ needs.check-next-tag-version.outputs.new_tag }}
          PACKAGE_VERSION="$(echo $PACKAGE_TAG | sed -E 's/[a-zA-Z]|-[a-zA-Z0-9]+//g')"
          echo "Package Version: $PACKAGE_VERSION"

          update_package_version_file () {
            git checkout $1 || true
            echo "__version__ = '$PACKAGE_VERSION'" > ./src/dsmlpstoragecontrollerclient/__init__.py
            git add ./src/dsmlpstoragecontrollerclient/__init__.py 
            git commit -m "updated version number"
            git push origin $1
          }

          update_package_version_file "develop"
          update_package_version_file "main"
  update-tag-version:
    name: Update tag version
    needs: update-init-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main