name: tag-version
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.NHP002_PERSONAL_ACCESS_TOKEN }}

jobs:
  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version-bump.outputs.tag }}
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: version-bump
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
  update-init-version:
    name: Update __init__ Version
    runs-on: ubuntu-latest
    needs: tag-version
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
      - name: Write version to __init__
        run: |
          git config --global user.email "nhp002@ucsd.edu"
          git config --global user.name "Naval Patel"
          PACKAGE_TAG=${{ needs.tag-version.outputs.tag }}
          PACKAGE_VERSION=$(echo $PACKAGE_TAG | sed -E 's/[a-zA-Z]|-[a-zA-Z0-9]+//g')
          echo "Package Version: $PACKAGE_VERSION"

          git checkout develop
          echo '__version__ = \"$PACKAGE_VERSION\"' > ./src/dsmlpstoragecontrollerclient/__init__.py
          git add ./src/dsmlpstoragecontrollerclient/__init__.py
          git commit -m "updated version number"
          git push origin develop

          git checkout main
          echo '__version__ = \"$PACKAGE_VERSION\"' > ./src/dsmlpstoragecontrollerclient/__init__.py
          git add ./src/dsmlpstoragecontrollerclient/__init__.py
          git commit -m "updated version number"
          git push origin main